config/routes.rb
Rails.application.routes.draw do

  root 'lists#index'

  resources :lists
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/to_do_list.rb
class ToDoList < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = ToDoList.all
  end

  def show
    @list = ToDoList.find(params[:id])
  end

  def new
    @list = ToDoList.new
  end

  def create
    @list = ToDoList.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def edit
    @list = ToDoList.find(params[:id])
  end

  def update
    @list = ToDoList.find(params[:id])
    if @list.update(list_params)
      redirect_to list_path(@list)
    else
      render :edit
    end
  end

  def destroy
    @list = ToDoList.find(params[:id])
    @list.destroy
    redirect_to list_path
  end

  private
      def list_params
        params.require(:list).permit(:title, :body)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<h1>Edit Lists</h1>
<hr />

<%= form_for @list do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, autofocus: true %>
  <br />

  <%= f.label :body %>
  <%= f.text_area :body %>
  <br />

  <%= f.submit %>
<% end %>

app/views/lists/index.html.erb
<h1>All Lists</h1>
<hr />

<%= link_to 'Create New List', new_list_path %>

<% if @lists.empty? %>
  <h3>No Lists Found, Please Create One!</h3>
<% else %>
  <ul>
    <% @lists.each do |list| %>
      <li>
        <%= link_to list.title, list_path(list)%>
        <span> - </span>
        <%= link_to 'Edit', edit_list_path(list[:id]) %>
        <span> - </span>
        <%= link_to 'Delete', list_path(list), method: :delete %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/lists/new.html.erb
<h1>Edit Lists</h1>
<hr />

<%= form_for @list do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br />

  <%= f.label :body %>
  <%= f.text_area :body %>
  <br />

  <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<h1>
  <%= @list.title %>
</h1>
<hr />

<blockquote>
  <%= @list.body %>
</blockquote>

<i>
  Posted At: <%= @list.created_at %>
</i>

<br />
<%= link_to 'All Lists', lists_path %>